### ISSUE TITLE
bulk_add: What is the item_id?

### ISSUE THREAD

**Issue by Findus23** [rakanalh/pocket-api#5]
Maybe I am missing something obvious, but what should I use as `item_id` when I am adding new URLs?
I tried to use incremental numbers, but I am getting titles and preview images of sites I haven't added.

**Comment by rakanalh** [comment]
Hello @Findus23,

According to the documentation:
https://getpocket.com/developer/docs/v3/modify#action_add

> url       The url of the item; provide this only if you do not have an item_id.

So basically you can pass an empty id or None and attach a url keyword argument to the call which is going to achieve the goal of bulk adding urls.

**Comment by Findus23** [comment]
Thanks for the help,
It now works, but it is a bit counterintuitive as it is a required parameter.
