### ISSUE TITLE
Does This API Wrapper Provide The Tags of Each Article?

### ISSUE THREAD

**Issue by Kiwibp** [rakanalh/pocket-api#6]
I have successfully used the library to extract my list but it appears that the tags aren't included.  I see from the readme file that tags can be edited but I'm not understanding why they aren't included as a key/value pair like the rest of the info is.  Please let me know if I'm missing something or if this wrapper doesn't provide the tags associated with each article.  Thank you!

``{'excerpt': 'to see the full lecture go to https://youtu.be/pCceO_D4AlYIn this lecture, he begins discussing the development of modern trait theory. Psychologists, expert in measurement and statistics, discovered extraversion, neuroticism, agreeableness, conscientiousness and openness to experience, and began th',
 'favorite': '0',
 'given_title': 'https://www.youtube.com/watch?v=j6fa_3CxgSY',
 'given_url': 'https://www.youtube.com/watch?v=j6fa_3CxgSY',
 'has_image': '1',
 'has_video': '2',
 'is_article': '0',
 'is_index': '0',
 'item_id': '1874276490',
 'resolved_id': '1874276490',
 'resolved_title': 'Jordan Peterson Breaks down the Brain',
 'resolved_url': 'https://www.youtube.com/watch?v=j6fa_3CxgSY',
 'sort_id': 850,
 'status': '0',
 'time_added': '1504484290',
 'time_favorited': '0',
 'time_read': '0',
 'time_updated': '1504484290',
 'word_count': '0'}``

**Comment by rakanalh** [comment]
Hi @Kiwibp,

This API wrapper returns exactly what is provided by Pocket. According to the documentation:
https://getpocket.com/developer/docs/v3/retrieve
This should return the list of tags you've assigned to the article. If `tags` member of the returned dictionary doesn't contain `tags` then there are no tags assigned to the article.

Am closing this issue as there's nothing i can do regarding this.

**Comment by Kiwibp** [comment]
Thank you.  I am new to API's and python so I was a little confused.  It appears that this is a wrinkle in the pocket API and not your wrapper.  [https://github.com/tapanpandita/pocket/issues/18](url)

Thanks for the guidance.  All set.  Also thanks for this wrapper!
